### ISSUE TITLE
Front end web server dependency

### ISSUE THREAD

**Issue by jthomp13** [18F/hello-ampd#28]
Hey, so for the site description ticket on the Microsoft Teams revAMPD kanban board I was figuring a static HTML page would be an easy way to finish the task, which I think would make it a dependency on the front end web server. What needs to be done to get that up and running?

Thanks

**Comment by ryanhofdotgov** [comment]
I'll be adding a front end server that will call the backend API server this week. I'll be pulling a stock NGINX web server container down in the docker compose file (for local development), populate it with some basic HTML/JS, and deploy it in conjunction with the backend server. 

I'll make corresponding changes to the cloud.gov deployment manifest.

This issue should be moved into the todo column of this week's sprint board, once last week's work gets tagged, it's board closed, and new sprint board created.

**Comment by ryanhofdotgov** [comment]
Note: You can create sprint boards in advance – this would be required for planning a beyond the current sprint – but for this example project, I have that step as part of the end-of-sprint release process.

**Comment by maheese** [comment]
@ryanhofdotgov this issue has a due date of 9/16 on our Teams board because there are other issues that depend on it (changing the site name, adding a site description, downloading emissions data).
