### ISSUE TITLE
Add site description

### ISSUE THREAD

**Issue by jthomp13** [18F/hello-ampd#36]
There is currently a ticket on the RevAMPD Kanban, for adding some information on EPA's programs and our data. Now that the web server is up, it should be pretty easy to add some paragraphs on it on the website's index page.

**Comment by ryanhofdotgov** [comment]
@jthomp13 I don't think this went through a review and merge into the develop branch. Was that intended?

**Comment by ryanhofdotgov** [comment]
Sorry – to clarify, usually the corresponding PR for an issue (https://github.com/18F/revampd/pull/38) would be reviewed and merged before its issue was closed.

**Comment by jthomp13** [comment]
Sorry, I misread a posting and I thought that the PR was already merged. I should have checked the pull request first.

**Comment by ryanhofdotgov** [comment]
@jthomp13 No worries – would you explicitly request a reviewer on your PR? On many teams, PRs will just sit until someone is assigned to review.

**Comment by ryanhofdotgov** [comment]
Addressed with https://github.com/18F/revampd/pull/38
